FROM mcr.microsoft.com/dotnet/sdk@sha256:7fd287cec03e027e39be13fb06ca1347f1338c7a6ab4ad305d94d91852693f70
RUN dotnet tool install -g dotnet-format
ENV PATH="/root/.dotnet/tools:"
WORKDIR /workspace
ENTRYPOINT ["dotnet","format"]